#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testArgumentType", testArgumentType),
        ("testCommand", testCommand),
        ("testCommandError", testCommandError),
        ("testDirectArgument", testDirectArgument),
        ("testEnumerationOption", testEnumerationOption),
        ("testFormatting", testFormatting),
        ("testHelp", testHelp),
        ("testLanguage", testLanguage),
        ("testLocalizations", testLocalizations),
        ("testNoColour", testNoColour),
        ("testOption", testOption),
        ("testVersion", testVersion),
    ]
}

extension InternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InternalTests = [
        ("testDirectArguments", testDirectArguments),
        ("testEmptyCache", testEmptyCache),
        ("testExportInterface", testExportInterface),
        ("testOptions", testOptions),
        ("testSetLanguage", testSetLanguage),
        ("testVersionSelection", testVersionSelection),
        ("testVersionSubcommand", testVersionSubcommand),
    ]
}

extension ReadMeExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReadMeExampleTests = [
        ("testParrot", testParrot),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(InternalTests.__allTests__InternalTests),
        testCase(ReadMeExampleTests.__allTests__ReadMeExampleTests),
    ]
}
#endif
