# .travis.yml
#
# This source file is part of the SDGCommandLine open source project.
# https://sdggiesbrecht.github.io/SDGCommandLine/macOS
#
# Copyright ©2017 Jeremy David Giesbrecht and the SDGCommandLine project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - os: osx
      env:
        - JOB="macOS"
      osx_image: xcode9
      script:
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: linux
      dist: trusty
      env:
        - JOB="Linux"
        - SWIFT_VERSION=4.0
      script:
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"
    - os: osx
      env:
        - JOB="Misc."
      osx_image: xcode9
      script:
        - "brew update"
        - "brew outdated swiftlint || brew upgrade swiftlint"
        - "bash ./Refresh\\ Workspace\\ \\(macOS\\).command"
        - "bash ./Validate\\ Changes\\ \\(macOS\\).command"

cache:
  directories:
  - $HOME/.Workspace
